Repository helloworld-ynovlyon/webapp-helloworld, pull requests merged in 2022-02, with the labels that each got.

#11 ci: add firebase to hosting & script to auto-deploy
  .firebaserc
  .github/workflows/firebase-hosting-merge.yml
  .github/workflows/firebase-hosting-pull-request.yml
  firebase.json
Labels: infra

#24 Feat/readme
  README.md
  src/assets/images/logo.svg
  src/assets/images/readme/home.png
  src/assets/images/readme/map.png
Labels: Poids : 1, feature

#41 Feat/profile
  package-lock.json
  package.json
  src/assets/styles/scss/_header.scss
  src/assets/styles/scss/_passport.scss
  src/assets/styles/scss/main.scss
  src/components/Footer.jsx
  src/components/Header.jsx
  src/pages/Passport/Passport.jsx
  src/router/passportRoutes.js
  src/router/routes.js
  src/router/userRoutes.js
Labels: Poids : 3, feature

#44 ci (release): add file to config ci auto release
  .github/workflows/1-create-release.yml
  .github/workflows/2-release.yml
Labels: ci

#46 chore(master): release 1.0.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending
